### ISSUE TITLE
Libre Office usage instructions need to be updated

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playwrite#53]
I tested the font installation on Ubuntu and used them on LibreOffice. During this process, I found out that the usage instructions on LibreOffice need updating. 

The styles are accessible but require a not-quite-straightforward process. To do so, you need to go to Format -> Character and then use the "Typeface" dropdown menu.

<img width="685" alt="Screen Shot 2024-05-03 at 18 11 55" src="https://github.com/TypeTogether/Playwrite/assets/48698976/2c5bebe3-0281-4f0c-8728-d45c137f606b">

However, the weird thing is, for some reason, they also list Italic, Bold, and Bold Italic instances that the font doesn't include.

Please update the usage instructions for that app in the PDF.

**Comment by vv-monsalve** [comment]
We also identified the need to add the following small paragraph in the "Instructions on using Playwrite" section:

```
This font family doesn't include true Bold or Italic styles, so please avoid using them – if you do use the common 'B' and 'I' buttons, you will get automatically generated styles that are low quality.
``` 
Next to the one that is there

> The Playwrite font family uses complex OpenType features to generate connected writing. Some common applications require these features to be manually activated.

**Comment by vv-monsalve** [comment]
Solved [here](https://www.primarium.info/Playwrite_installation_notes.pdf)

**Comment by kenmcd** [comment]
This is not correct - and is just confusing.
The fonts are available in the normal font list.
That `Character > Typeface` is (was) an attempt to to support large font families using the Typo names.
AFAIK it has never worked properly (as you can see).
Sending users there is a a bad idea.

What is the `Maximum` font?
It has a name conflict with the Regular.

**Comment by vv-monsalve** [comment]
> This is not correct - and is just confusing.

Could you please clarify what is not _correct_?

> The fonts are available in the normal font list.

Not all the styles included in the font are accessible through the font menu. The Character -> Typeface menu will allow users to access all the styles, despite the fact it also displays the other instances.

> What is the Maximum font?

It is the regular.

**Comment by kenmcd** [comment]
> > The fonts are available in the normal font list.
> 
> Not all the styles included in the font are accessible through the font menu. The Character -> Typeface menu will allow users to access all the styles, despite the fact it also displays the other instances.
> 

Been a long time since I installed LibreOffice, but I think the default toolbars include the `Formatting` toolbar in which I have the font list open in in the image below. The `Standard (Single Mode)` toolbar (the top one in the image) also has the same font selector. One of these is enabled by default.
And I see the correct 4 fonts available.

![LibreOffice-Toolbars](https://github.com/TypeTogether/Playwrite/assets/844920/07f4c07f-602f-43a6-a2e3-ea953f7c1ca6)


That other way to select the fonts has been broken for a long time, and still is, as you can see.
So I think sending a user there is going to be really confusing.
The question is going to be: _"Why are the Bold and Italic fonts not working?"_


> > What is the Maximum font?
> 
> It is the regular.

I guess that is what has me confused - each family in the repo `fonts` folder has both a `Regular` and a `Maximum` font. So if a user tried to install them all (and they will), there would be a name conflict.

**Comment by vv-monsalve** [comment]
> And I see the correct 4 fonts available.

Please specify the OS and the app version number.

<br>

> (is this not what you see?)

It is not. This is what I see
<img width="1096" alt="Screen Shot 2024-05-22 at 17 27 40" src="https://github.com/TypeTogether/Playwrite/assets/48698976/78a87042-857c-4921-b27a-bee1af62d4d5">

On `macOS 12.6.3` LibreOffice  `7.5.0.3 (X86_64) / LibreOffice Community`

However, we are aware that all the styles are listed in Windows. So perhaps the Note could clarify the Character -> Typeface option is necessary on macOS only.

<br>

> each family in the repo `fonts` folder has both a `Regular` and a `Maximum` font

Please point at what you find as `Maximum` (link or image) to clarify your finding.

**Comment by kenmcd** [comment]
> Please specify the OS and the app version number.

Windows 10, LibreOffice v24.2.3.2 (X86_64) / LibreOffice Community

Your screenshot image is very odd to me. 
Maybe that is because it is the Mac version.
I have tested in the Linux version, and it looks the same as mine.

Will install latest LO in a macOS 14.5 Sonoma VM and test.
If it is selecting via the typo family, there should be a Font Style selector.
Odd. I will take a look.

> Please point at what you find as `Maximum` (link or image) to clarify your finding.

From the `fonts` folder in this repo.
(same thing in your fork repo)

![PlaywriteCO](https://github.com/TypeTogether/Playwrite/assets/844920/0cb3e685-e119-47a1-aaf6-3dd33832f36d)

**Comment by vv-monsalve** [comment]
> If it is selecting via the typo family, there should be a Font Style selector.
> Odd. I will take a look.

Excellent. Ty.

<br>

> From the fonts folder in this repo.

Ah! in the ttf sub-folder. We have been working on and testing the Variable fonts, which are the target for GF. The zip file downloaded from there will only include the four correspondent static TTFs. 

@simoncozens it seems builder is producing this `Maximum` fonts.

**Comment by kenmcd** [comment]
> > If it is selecting via the typo family, there should be a Font Style selector.
> > Odd. I will take a look.
> 
> Excellent. Ty.

I am seeing what you are seeing - and it makes no sense.
LO support for Mac was not good that I remember (back when I was spending a lot of time in the LO bug tracker), but this is just weird.
Like I said, that particular interface to the Typo Family and Style never worked properly in Windows, or Linux back then.
And it appears it is still not working properly now.
I will poke around the LO bug tracker tomorrow and see if this has been discussed (probably has).

**Comment by khaledhosny** [comment]
> Maybe that is because it is the Mac version.

Indeed it is the case. Core Text API has no way of listing font families using R/B/I/BI model, nor it give access to all name IDs so that client software that needs this model can use it. So LibreOffice on macOS uses typographic family names (even though it is ill-prepared to handle families with styles other than R/B/I/BI).
